project:
  type: website

website:
  title: "Georgios Douzas"
  search: true
  
  navbar:
    right:
      - icon: github
        href: https://github.com/georgedouzas
      - icon: linkedin
        href: https://www.linkedin.com/in/gdouzas

execute:
  cache: true
  freeze: auto