project:
  type: website

website:
  title: "AI & Friends"
  navbar:
    right:
      - about.qmd
      - cv.md
      - icon: github
        href: https://github.com/
format:
  html:
    theme: litera
    css: styles.css

execute:
  cache: true
  freeze: auto