project:
  type: website

website:
  title: "AI & Friends"
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/georgedouzas
      - icon: linkedin
        href: https://www.linkedin.com/in/gdouzas
format:
  html:
    theme: minty
    css: styles.css

execute:
  cache: true
  freeze: auto